ifconfig tap1 promisc up
ifconfig tap2 promisc up
ifconfig tap3 promisc up
ifconfig tap4 promisc up
ifconfig tap5 promisc up
ifconfig tap6 promisc up
ifconfig tap7 promisc up
ifconfig tap8 promisc up
ifconfig tap9 promisc up
ifconfig tap10 promisc up
